name: Simple Test Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      stripemock:
        image: stripe/stripe-mock:latest
        ports: ['12111:12111']

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: |
        echo "Run your test commands here. The stripe-mock service is available at localhost:12111"
